#!/bin/bash
# Use !/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FILES_LIST="bashrc zshrc screenrc gitconfig vim tmux.conf"
FILE_LIST_GIT_MULTI="bashrc zshrc screenrc gitconfig gitconfig-personal gitconfig-work vim tmux.conf"
NOW=$(date +"%Y%m%d")
BACKUP="no"
INSTALL="no"
SYMLINK="no"

# HELP Message.
usage() {
    cat 1>&2 <<EOF
Usage: $0 [-b] [-i] [-h]
    -b Backup old file
    -i Install dotfiles [Rewrite existing files]
    -s Symlinking dotfiles [Rewrite existing files]
    -h Print HELP message
EOF
    exit 1
}

# Without any parameter print HELP message.
if [ $# -eq 0 ];
then
    usage;
fi

# Paprsing script parameters.
while getopts 'bish' opt; do
    case "${opt}" in
        b) BACKUP=yes ;;
        i) INSTALL=yes ;;
        s) SYMLINK=yes ;;
        h) usage ;;
        *) echo "Unknown option $opt" 1>&2; usage ;;
    esac
done
shift $(( $OPTIND - 1 ))

# Check if git ins installed
# if type -P git &>/dev/null; then
if [ ! -x "$(command -v git)" ]; then
    echo "Missing git binary !!!"
    echo "Can't continue without it. Please install git before you continue."
    exit 1
fi

# Setup EMAIL and NAME for gitconfig.tmpl
read -n 1 -p "Do you have personal and work git account? (Y/n) " more_accounts
case $more_accounts in
    Y|y)
        FILES_LIST=$FILE_LIST_GIT_MULTI
        cp gitconfig-multi gitconfig
        echo -e "\nPlease provide your name and email address to be used for personal account"
        read -p "Enter your name: " name
        read -p "Enter your email: " email
        sed -e "s/{{NAME}}/$name/g" -e "s/{{EMAIL}}/$email/g" gitconfig-personal.tmpl > gitconfig-personal
        echo "Please provide your name and email address to be used for work account"
        read -p "Enter your name: " name
        read -p "Enter your email: " email
        sed -e "s/{{NAME}}/$name/g" -e "s/{{EMAIL}}/$email/g" gitconfig-work.tmpl > gitconfig-work
        ;;
    *)
        echo "Please provide your name and email address to be used in .gitconfig file"
        read -p "Enter your name: " name
        read -p "Enter your email: " email
        sed -e "s/{{NAME}}/$name/g" -e "s/{{EMAIL}}/$email/g" gitconfig.tmpl > gitconfig
        ;;
esac

# Rename any existing dotfilesk.
for FILE in $FILES_LIST; do
    # backuping old files if requested.
    if [ "$BACKUP" == "yes" ];
    then
        echo "Backuping ~/.$FILE to ~/.$FILE-$NOW"
        mv ~/.$FILE ~/.$FILE-$NOW
    fi

    # Symlinking dot file to HOME directory.
    if [ "$SYMLINK" == "yes" ];
    then
        echo "Create symlink to $FILE in home directory"
        rm -rf ~/.$FILE
        ln -s $BASEDIR/$FILE ~/.$FILE
    # Copy dot file in to the HOME directory.
    elif [ "$INSTALL" == "yes" ];
    then
        echo "Copy $FILE in to the HOME directory"
        rm -rf ~/.$FILE
        cp -r $BASEDIR/$FILE ~/.$FILE
    fi
done
