#!/bin/bash
# Use !/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FILES_TO_LINK="bashrc screenrc gitconfig vim"
NOW=$(date +"%Y%m%d")
BACKUP="no"
INSTALL="no"

# DEBUG messages.
#echo "PWD: $BASEDIR"
#echo "NOW=$NOW"

# HELP Message.
usage() {
	cat 1>&2 <<EOF
Usage: $0 [-b] [-i] [-h]
	-b Backup old file
	-i Install dotfiles [Rewrite existing files]
	-h Print HELP message
EOF
	exit 1
}

if [ $# -eq 0 ];
then
	usage;
fi

# Paprsing script parameters.
while getopts 'bih' opt; do
	case "${opt}" in
		b) BACKUP=yes ;;
		i) INSTALL=yes ;;
		h) usage ;;
		*) echo "Unknown option $opt" 1>&2; usage ;;
	esac
done
shift $(( $OPTIND - 1 ))

# Rename any existing dotfilesk.
for FILE in $FILES_TO_LINK; do
	# backuping old files if requested.
	if [ "$BACKUP" == "yes" ];
	then
		echo "Backuping ~/.$FILE to ~/.$FILE-$NOW"
		mv ~/.$FILE ~/.$FILE-$NOW
	fi

	# Symlinking dot file to HOME directory.
	if [ "$INSTALL" == "yes" ];
	then
		echo "Create symlink to $FILE in home directory"
		ln -s $BASEDIR/$FILE ~/.$FILE
	fi
done

# Installing git submodules
echo "Installing git submodules"
git submodule update --init --recursive
