" A sensible vimrc for Python and Go development with Ansible support.

" vim-plug installation if not exists
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Themes
Plug 'morhetz/gruvbox'

" fzf
" if binary is already installed this line is not needed.
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" File manager
Plug 'preservim/nerdtree'

" Templ
Plug 'joerdav/templ.vim'

" Autocompletion
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Expanding abbreviations similar to emmet.
"  https://medium.com/vim-drops/be-a-html-ninja-with-emmet-for-vim-feee15447ef1
"  https://alldrops.info/posts/vim-drops/2018-08-21_become-a-html-ninja-with-emmet-for-vim/
Plug 'mattn/emmet-vim'

" Comment stuff
Plug 'tpope/vim-commentary'

" Git
Plug 'tpope/vim-fugitive'

" Status line
Plug 'vim-airline/vim-airline'

"call vundle#end()
call plug#end()

""""""""""""""""""""""
"      Settings      "
""""""""""""""""""""""
set nocompatible                " Enables us Vim specific features
set laststatus=2                " Show status line always
set encoding=utf-8              " Set default encoding to UTF-8
set autoindent                  " Enable Auto indentation
set incsearch                   " Shows the match while typing
set hlsearch                    " Highlight found searches
set noerrorbells                " No beeps
set number                      " Show line numbers
set noswapfile                  " Don't use swapfile
set nobackup                    " Don't create annoying backup files
set splitright                  " Vertical windows should be split to right
set splitbelow                  " Horizontal windows should split to bottom
set noshowmode                  " We show the mode with airline or lightline
set ignorecase                  " Search case insensitive...
set smartcase                   " ... but not it begins with upper case
set completeopt=menu,menuone    " Show pop-up menu, even if there is one entry
set pumheight=10                " Completion window max size
set nocursorcolumn              " Do not highlight column (speeds up highlighting)
set cursorline                  " Highlight current line
set undolevels=1000             " How many undos
set undoreload=1000             " number of lines to save for undo
set history=1000                " Remember more commands and search history
set nofoldenable                " Don't fold by default
set tabstop=2                   " Tabs will be displayed as 2 spaces
set shiftwidth=2                " Number of space characters inserted for indentation
set expandtab                   " Insert space characters whenever the tab key is pressed
set ttimeoutlen=10              " Key code delays
set timeoutlen=1000             " Papping delays ms
set updatetime=100              " Smaller updatetime for CursorHold & CursorHoldI
set fo-=t                       " Don't automatically wrap text when typing

" Auto reload vimrc when it's saved
augroup vimrc
    autocmd!
    autocmd BufWritePost vimrc source %
augroup end

" Languages settings
augroup languages
    autocmd!
    autocmd Filetype gitcommit setlocal spell textwidth=72
    autocmd BufRead,BufNewFile */playbooks/*.yml set filetype=ansible
    autocmd FileType yaml setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
    autocmd FileType json setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
    autocmd FileType html setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
    autocmd FileType javascript,typescript  setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
    autocmd FileType sh,bash setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
    autocmd InsertLeave * set nopaste " Disable paste mode when leaving Insert Mode
augroup end

" Enable to copy to clipboard for operations like yank, delete, change and put.
if has('unnamedplus')
    set clipboard^=unnamed
    set clipboard^=unnamedplus
endif

" This enables to undo files even if you exit Vim.
if has('persistent_undo')
    set undofile
    set undodir=~/.vim/undo/
endif

" Suggestion: show info for completion candidates in a popup menu
if has("patch-8.1.1904")
  set completeopt+=popup
  set completepopup=align:menu,border:off,highlight:Pmenu
endif

" Wrap line in diff mode
if &diff
  set wrap
  set linebreak
  set showbreak=↪
  set display+=lastline
endif

" Color scheme
filetype on
syntax enable
set background=dark

if (has("termguicolors"))
    set termguicolors
endif

" 80 character's marker
"let &colorcolumn=join(range(80,999),",")
set colorcolumn=80

try
    " Enable italic font
    let g:gruvbox_italic=1
    colorscheme gruvbox
catch /^Vim\%((\a\+)\)\=:E185/
    colorscheme default
endtry

" Spell checking change highlighting to underline
highlight clear SpellBad
highlight SpellBad cterm=underline ctermbg=66 ctermfg=235
highlight clear SpellRare
highlight SpellRare cterm=underline ctermbg=66 ctermfg=235
highlight clear SpellCap
highlight SpellCap cterm=underline ctermbg=66 ctermfg=235
highlight clear SpellLocal
highlight SpellLocal cterm=underline ctermbg=66 ctermfg=235

" Custom Invisible
set listchars=tab:»·,nbsp:+,trail:·,extends:→,precedes:←
set showbreak=↳

" F1-F12 key calls
" F2: Disable formatting when pasting large chunks of code.
set pastetoggle=<F2>

" F3: Toggle line numbers.
nnoremap <silent> <F3> :silent set number! number?<CR>
imap <silent> <F3> <C-o>:set number! number?<CR>

" F4: Toggle list (display unprintable characters).
nnoremap <silent> <F4> :silent set list! list?<CR>

" F5: Show NERDTree.
nnoremap <silent> <F5> :NERDTreeToggle<CR>

" F12: Spell checking
" Once the cursor is on the word, use z=, and Vim will suggest a list of
" alternatives that it thinks may be correct.
nnoremap <silent> <F12> :set spell!<CR>

" Change the mapleader from \ to ,
let mapleader=","
" Map ; to : and save a million keystrokes ;)
"nnoremap ; :

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Select all text in current buffer
"map <Leader>a ggVG

" Re-indent entire buffer
"map <leader>f gg=G

" Clear search highlighting
nnoremap <silent> <C-n> :nohlsearch<CR>
vnoremap <silent> <C-n> :nohlsearch<CR>
inoremap <silent> <C-n> <C-o>:nohlsearch<CR>

" Copy/paste from system clipboard
noremap <Leader>y "*y
noremap <Leader>p "*p
noremap <Leader>Y "+y
noremap <Leader>P "+p

" Easy window navigation
" Navigating requires you to press Ctrl first, then a navigation keys
nnoremap <C-UP> <C-W><C-K>
nnoremap <C-DOWN> <C-W><C-J>
nnoremap <C-LEFT> <C-W><C-H>
nnoremap <C-RIGHT> <C-W><C-L>
" Navigating requires you to press Ctrl first, then h,j,k,l
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Use + and - to increase or decrease split windows by a sane amount.
nnoremap <silent> + :exe "resize +10"<CR>
nnoremap <silent> - :exe "resize -10"<CR>
nnoremap <silent> <Leader>+ :exe "vertical resize +10"<CR>
nnoremap <silent> <Leader>- :exe "vertical resize -10"<CR>

" Tab navigation.
nnoremap <Leader>n :tabprevious<CR>
nnoremap <Leader>m :tabnext<CR>
nnoremap <Leader>1 1gt
nnoremap <Leader>2 2gt
nnoremap <Leader>3 3gt
nnoremap <Leader>4 4gt
nnoremap <Leader>5 5gt
nnoremap <Leader>6 6gt
nnoremap <Leader>7 7gt
nnoremap <Leader>8 8gt
nnoremap <Leader>9 9gt
nnoremap <Leader>0 :tablast<CR>

"vim-fugitive
nnoremap <leader>gs :Git<CR>
nnoremap <leader>gc :Git commit<CR>
nnoremap <leader>gp :Gpush<CR>
nnoremap <leader>gd :Gdiff<CR>

" COC GoTo code navigation.
nnoremap <silent> gd <Plug>(coc-definition)
nnoremap <silent> gy <Plug>(coc-type-definition)
nnoremap <silent> gi <Plug>(coc-implementation)
nnoremap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
"nnoremap <silent> K :call <SID>show_documentation()<CR>
nnoremap K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" Symbol renaming.
nnoremap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
nnoremap <leader>f <Plug>(coc-format-selected)

"nmap <C-F> :FZF<CR>
"nmap <C-P> :Files<CR>
nnoremap <C-P> :GFiles<CR>
nnoremap <C-G> :Rg<CR>

" Customize fzf colors to match your color scheme
" - fzf#wrap translates this to a set of `--color` options
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" Coc spell checker
" Then positioning the cursor in the word, any of the following should display
" the list of suggestions:
" - <leader>aap for current paragraph
" - <leader>aw for current word
xnoremap <leader>a <Plug>(coc-codeaction-selected)
nnoremap <leader>a <Plug>(coc-codeaction-selected)

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice.
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Remove all whitespace
nnoremap <Leader>w :%s/\s\+$//<CR>

""""""""""""""""""""""
"  Plugins settings  "
""""""""""""""""""""""
" Airline
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#tab_nr_type = 1
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#tabline#show_buffers = 0
let g:airline_theme='gruvbox'

if !exists('g:airline_symbols')
let g:airline_symbols = {}
endif

let g:airline_left_sep=''
let g:airline_right_sep=''
" let g:airline_symbols.branch = 'git:'
let g:airline_symbols.branch = '⎇ '
let g:airline_symbols.linenr = ' Ln:'
let g:airline_symbols.colnr = ' Col:'
"let g:airline_symbols.linenr = '¶'
let g:airline_symbols.readonly = 'RO'
"let g:airline_symbols.whitespace = 'Ξ'
let g:airline_symbols.maxlinenr= ''
" Define which filetypes have special treatment of /* */ comments.
" let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline#extensions#c_like_langs = ['c', 'cpp', 'go', 'javascript']
let g:airline#extensions#tabline#fnamemod = ':t'

" emmet-vim
let g:user_emmet_leader_key=','

" NERDTree
let g:NERDTreeShowHidden = 1
let g:NERDTreeQuitOnOpen = 1

" coc.nvim
let g:coc_global_extensions = ['coc-sh', 'coc-git', 'coc-tsserver', 'coc-json', 'coc-yaml', 'coc-html', 'coc-css', 'coc-pyright', 'coc-go', 'coc-spell-checker', 'coc-prettier']
